'''

Battlecry        (DONE)
Choose One       (DONE)
Combo            (DONE)
Deathrattle      (DONE)
Discover         (DONE)
Divine Shield    (DONE)
Freeze           (DONE)
Lifesteal        (DONE)
Poisonous        (DONE)
Outcast          (DONE)
Overload         (DONE)
Taunt            (DONE)
Choose Twice     (DONE)
Inspire          (DONE)
Start of Game    (DONE)
Casts When Drawn (DONE)
Immune           (DONE)
Reborn           (DONE)
Twinspell        (DONE)
Charge           (DONE)
Echo             (DONE)
Corrupt          (DONE)
Overkill         (DONE)
Rush             (DONE)
Windfury         (DONE)
Mega-Windfury    (DONE)
Stealth          (DONE)
Silence          (DONE)
Spell Damage     (DONE)

Recruit          (Not Implemented)
Dormant          (Not Implemented)
Frenzy           (Not Implemented)
Honorable Kill   (Not Implemented)
Magnetic         (Not Implemented)
Spellburst       (Not Implemented)
Invoke           (Not Implemented)
Adapt            (Not Implemented)
Secret           (Not Implemented)
Passive          (Not Implemented)
Tradeable        (Not Implemented)
Sidequest        (Not Implemented)
Quest            (Not Implemented)
Questline        (Not Implemented)

'''