'''

------ FUNCTIONS ------
Battlecry        (DONE)
Combo            (DONE)
Deathrattle      (DONE)
Outcast          (DONE)
Inspire          (DONE)
Start of Game    (DONE)
Casts When Drawn (DONE)
Overkill         (DONE)
Frenzy           (DONE)
Honorable Kill   (DONE)
Spellburst       (DONE)
-----------------------

Choose One       (DONE)
Discover         (DONE)
Divine Shield    (DONE)
Freeze           (DONE)
Lifesteal        (DONE)
Poisonous        (DONE)
Overload         (DONE)
Taunt            (DONE)
Choose Twice     (DONE)
Immune           (DONE)
Reborn           (DONE)
Twinspell        (DONE)
Charge           (DONE)
Echo             (DONE)
Corrupt          (DONE)
Rush             (DONE)
Windfury         (DONE)
Mega-Windfury    (DONE)
Stealth          (DONE)
Silence          (DONE)
Spell Damage     (DONE)
Recruit          (DONE)
Tradeable        (DONE)
Dredge           (DONE)
Colossal         (DONE)
Adapt            (DONE)
Invoke           (DONE)
Dormant          (DONE)
Counter          (DONE)
Magnetic         (DONE)
Secret           (DONE)
Sidequest        (DONE)
Quest            (DONE)
Questline        (DONE)

Passive          (Not Implemented) [This is not a priority since as far as I know, there are no cards that have this in the main game]

'''