services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata_prod:/var/lib/postgresql
  frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - ORIGIN=${DOMAIN}:${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
