services:
  registry-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./pgdata_prod:/var/lib/postgresql
  registry-frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - ORIGIN=${DOMAIN}
    ports:
      - 3002:3002
    depends_on:
      - registry-db
